server:
  port: 8081
#服务名称
spring:
  application:
    name: service-client-v1
#首先指定服务注册中心的地址为http://localhost:8080/eureka/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
