server:
  port: 8080
#首先指定服务注册中心的地址为http://localhost:8080/eureka/
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #关闭自我保护模式（缺省为打开）   
#服务名称eurka-server
spring:
  application:
    name: eurka-server

